### ISSUE TITLE
Try statement can be used for more than 1 line of code

### ISSUE THREAD

**Issue by cmcjacob** [captainmeta4/botbust#4]
`try: comment.subreddit.muted.add(comment.author, note="BotBusted!") except: pass try: comment.subreddit.banned.add(comment.author, note="BotBusted!", ban_message = BAN_MESSAGE.format(comment.subreddit.display_name, comment.author.name)) except:`

Why are you using two `try` statements here? You do realize that you can use more than one line of code inside a try block, right? I would issue a pull request but I feel like it's too basic of an issue, and one the creators here don't seem to understand.

It's a mistake this project repeatedly makes.

**Comment by captainmeta4** [comment]
Two try blocks are used because each statement needs to be attempted independently of the success/failure of the other.

**Comment by captainmeta4** [comment]
And that is the case throughout the project. The bot might have one mod permission, but not another. In that case, it should do everything it can, and fail gracefully (with `except: pass`) on the things it can’t.
