### ISSUE TITLE
Failed to detect banned bot

### ISSUE THREAD

**Issue by MarissaB** [captainmeta4/botbust#5]
On /r/Autodetailing the following bot posted a thread and BotBust failed to detect it despite being on BotBust's banned list: 

https://www.reddit.com/user/GeneralReposti_Bot/overview

Thread in question:

https://www.reddit.com/r/AutoDetailing/comments/dcsvj2/refinishing_the_center_console_in_an_audi_a6/

Edit: More info - we invited it to the sub 15 days ago with access/post/mail privileges. The bot account in question appears to have been blacklisted 4 days ago.

Edit 2: Happened on /r/spotted just now too.

**Comment by CAPNAMENOWUPVOTE** [comment]
Happened to me too:

https://www.reddit.com/r/JurassicPark/comments/dljbzi/i_spent_7_months_in_my_garage_making_this_and/

**Comment by tomkrizan** [comment]
Note: Longtime user of botbust and no other issues with it. Here's the thread that stated it was banned:

https://www.reddit.com/r/BotBust/comments/dayosp/overview_for_generalreposti_bot/

**Comment by MarissaB** [comment]
Author commented on Reddit that it doesn't watch submissions, only comments, which is unfortunate. https://www.reddit.com/r/BotBust/comments/bqyvdn/botbust_introduction_5_avas_entity_edition/f52od7k/?context=3

**Comment by captainmeta4** [comment]
Botbust only monitors comments
